name: file tree

on:
  workflow_dispatch:

jobs:
  file-tree:
    runs-on: self-hosted

    steps:
    - name: Install tree
      run: |
        sudo apt update
        sudo apt install -y tree

    - name: Generate file tree
      run: |
        time tree -a > filetreelist.txt
